#!/usr/bin/env bash
# tools/build_pe_stub.sh
#
# Regenerate src/pe_stub.rs from tools/pe_stub.c.
#
# Requires x86_64-w64-mingw32-gcc and x86_64-w64-mingw32-objcopy (both are
# installed in the rcm-server Docker image).
#
# The stub is compiled as a freestanding PE, then the .text section is
# extracted as a flat binary. Because the stub has no data references at
# all (kernel32 is found by PEB walk, every API by ROR13 hash), .text alone
# is position independent. `entry` is the only non-inlined function, so it
# sits at offset 0 of the section - the bootstrap in src/shellcode.rs calls
# the stub base directly.

set -euo pipefail
cd "$(dirname "$0")/.."

CC=x86_64-w64-mingw32-gcc
OBJCOPY=x86_64-w64-mingw32-objcopy
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

"$CC" -Os -fno-builtin -fno-ident -fno-asynchronous-unwind-tables \
      -fno-stack-protector -fomit-frame-pointer -nostdlib \
      -Wl,-e,entry -Wl,--build-id=none \
      tools/pe_stub.c -o "$WORK/pe_stub.exe"

"$OBJCOPY" -O binary --only-section=.text "$WORK/pe_stub.exe" "$WORK/pe_stub.bin"

SIZE=$(stat -c%s "$WORK/pe_stub.bin")
echo "[*] stub size: $SIZE bytes"

{
    echo "// src/pe_stub.rs - GENERATED by tools/build_pe_stub.sh, do not edit by hand."
    echo "// Source: tools/pe_stub.c. See that file for the loader contract."
    echo "pub const EXE_STUB_X64: &[u8] = &["
    od -A n -t x1 -v "$WORK/pe_stub.bin" | \
        sed 's/^ *//; s/ /, 0x/g; s/^/    0x/; s/$/,/'
    echo "];"
} > src/pe_stub.rs.new

mv src/pe_stub.rs.new src/pe_stub.rs
echo "[+] wrote src/pe_stub.rs"
